name: circular_menu_example
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  circular_menu:
    git:
      url: https://github.com/naeemeltaief-dojoon/circular_menu.git
  

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
